#!/usr/bin/env ruby

if ARGV.include?("--help") || ARGV.include?("-h")
  puts "usage: #$PROGRAM_NAME [arguments] - edit git status files passing arguments to editor"
else
  s = `git status --porcelain`
  s = s.split("\n")
  a = s.map{ |f| f.gsub(/.* /,'') }
  
  system "#{ ENV['EDITOR'] } #{ ARGV.join(' ') } #{ a.join(" ") }"
end
